######################################################################
# Automatically generated by qmake (3.0) Fri Apr 27 16:25:39 2018
######################################################################

TEMPLATE = app
TARGET = PlazzaGui
INCLUDEPATH += .

# Input
HEADERS += ui_plazzagui.h include/plazzagui.h include/ui_plazzagui.h
FORMS += plazzagui.ui
SOURCES += main.cpp plazzagui.cpp
QT += widgets
